### ISSUE TITLE
[BUG] 공유 알림에서 제목과 알림 날짜가 겹치는 현상이 발생합니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#10]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

공유 알림에서 제목과 알림 날짜가 겹칩니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 알림 아이콘
2. 문의 탭
3. 공유 탭

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

제목이 알림 날짜의 영역을 침범하지 않아야 합니다.

## 추가적인 설명
> 추가적으로 설명할 것이 있다면 설명해주세요,
![KakaoTalk_20240915_105639120_04](https://github.com/user-attachments/assets/61f1d847-37bf-4381-808c-0ea64c264b2f)

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.1에 수정하여 반영하였습니다
- width = 0 설정 후 constraint start와 end 연결 후 multiline, ellipse로 해결
