### ISSUE TITLE
[BUG] 이름 변경을 클릭하면 앱이 죽습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#11]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

이름 변경을 클릭하면 앱이 죽습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 내 정보 
2. 계정
3. 이름

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

이름 변경 창이 떠야합니다.

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.1에 수정하여 반영했습니다.
실시간 반영에는 문제가 있어 추가 반영하겠습니다

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.1에 실시간 반영문제 해결하여 반영하였습니다
- registerForActivityResult를 통해 해결
