### ISSUE TITLE
[BUG] 프로필 사진을 변경하지 못합니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#12]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

프로필 사진을 변경하지 못합니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 내 정보
2. 계정
3. 프로필 변경 아이콘
4. 사진 선택

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

내 계정의 프로필 사진이 변경되어야 합니다.

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.1에 수정하여 반영하였습니다.
- Retrofit2 인터페이스에서 @Multipart 어노테이션을 붙이고 @Header에 "Content-type"을 제거하여 해결했습니다
