### ISSUE TITLE
[BUG] 설정에 불필요한 버튼이 있습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#14]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

임시 공간 삭제, 테마 모드는 현재 지원하지 않는 탭입니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 내 정보

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

지원하지 않는 설정은 보이지 않게 처리해야 합니다.

**Comment by HaeBun** [comment]
hotfix-kit-1.0.1 버전에 다음과 같이 반영했습니다.
- 임시 공간 삭제 제거
- 테마 설정 제거

**Comment by HaeBun** [comment]
![issue_14_1](https://github.com/user-attachments/assets/7c682ead-a84f-4226-b543-459d5b258a2c)
