### ISSUE TITLE
[BUG] 알림 변경을 해도 적용되지 않습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#15]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

설정에서 알림 변경 하고 나간 다음 다시 알림 변경 탭에 들어가도 알림 변경이 이루어지지 않습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 내 정보
2. 알림 설정
3. 알림 변경
4. 페이지 나가기
5. 알림 설정

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

알림 설정이 정상적으로 변경되어야 합니다.

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.1에 이와 같이 반영하였습니다
- 뒤로가기 버튼 클릭 시 변경사항 api 전송
- 이전의 변경사항은 preference를 통해 관리

**Comment by dbstjdqls14** [comment]
@yyj1453 가져오기 반영하여 재수정 부탁드립니다
