### ISSUE TITLE
[BUG] 만료된 AccessToken에 대한 오류 처리가 되어있지 않습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#16]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

AccessToken 만료 시 앱이 켜지지 못하고 죽어버립니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 앱 실행 (단, AT가 만료된 상태)

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

1. 로그인 화면으로 이동

## 추가적인 설명
> 추가적으로 설명할 것이 있다면 설명해주세요,

![image](https://github.com/user-attachments/assets/c357a8f4-e0d2-4889-9713-21d95b659ef7)
앱이 죽었을 떄 서버 로그에는 만료된 AT 토큰이 출력되고 있었습니다.

**Comment by HaeBun** [comment]
hotfix-kit-1.0.3 버전에 반영했습니다.
토큰 만료 시 상황은 테스트 진행 후 이슈에 추가 반영하도록 하겠습니다.

**Comment by HaeBun** [comment]
다음과 같이 상황을 가정하여 AT, RT를 갱신 테스트 진행하였습니다.

1. 두 디바이스에서 로그인(맨 마지막 접근한 디바이스가 최신의 AT, RT를 소유).

2. 첫 번째 로그인 디바이스에서 재접속

3. 메인화면 이동 성공

해당 과정에서 성공적으로 메인화면 호출이 되었습니다.
AT, RT는 복수로 존재할 수 없기에 두 디바이스 간 앱 실행 시 토큰을 재발급 받는 로직에 문제가 없었습니다.
따라서 해당 이슈는 해결 처리 하도록 하겠습니다.
