### ISSUE TITLE
[BUG] 업로드 시 공유 인원 추가 버튼이 동작하지 않습니다. (Android 13)

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#18]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

업로드 시 공유 인원 추가 버튼이 동작하지 않습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 업로드
2. 공유 + 버튼 클릭

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

1. 사용자 공유 페이지로 이동

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.1에 수정하여 반영하였습니다
- 문서 단일 공유 기능 미구현으로 인해 삭제처리
- 문서 단일 공유 기능은 딥링크 기능 필요
