### ISSUE TITLE
[BUG] 하이라이트가 남아 사라지지 않습니다.

### ISSUE THREAD

**Issue by yyj1453** [Globa-Seoil-Univ/globa-android#20]
## 어떤 버그가 발생했나요?
- 문서 열람 시 댓글 창을 열었다 닫거나 단어 검색을 하고 돌아오면 하이라이트가 남아 사라지지 않습니다.
- 댓글 작성 시 바로 댓글 보기 버튼이 활성화되지 않고 하이라이트가 남아있습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
- 하이라이트 후 댓글 작성 버튼을 누르고 댓글 작성을 하지 않고 댓글 창을 닫기
- 하이라이트 후 단어 검색 버튼을 누른 후 돌아오기
-  댓글 최초 작성 후 댓글 창 닫기

## 기대 결과
- 댓글 창이나 단어 검색 창을 닫고 난 후 하이라이트 자동 삭제
- 댓글 최초 작성 후 댓글 창을 닫으면 하이라이트가 사라지고 댓글 버튼이 생김

## 추가적인 설명
- 아마도 onResume() 메소드에서 해결 해야할 것 같습니다

**Comment by HaeBun** [comment]
하이라이트 구분이 필요하여, 색상으로도 구분하였습니다.
1. 드래그한 하이라이트 = 노란색
2. 댓글 하이라이트 = 빨간색

문제
1. 드래그 하이라이트 후 댓글 작성 시, 하이라이트가 빨간색으로 변하지 않는 현상
2. 댓글 하이라이트가 남겨진 섹션에서는 드래그 하이라이트가 동작하지 않는 현상


해결 조건
하이라이트 처리는 SpannableString을 사용중이며,
사용자가 드래그 중이더라도 계속해서 댓글 하이라이트를 유지해야 합니다.

또한, 댓글 하이라이트가 남겨진 섹션은 드래그 하이라이트를 위한 SpannableString 처리를 진행 후,
그 위에 댓글 하이라이트의 기능이 남겨져야 한다.

**Comment by HaeBun** [comment]
hotfix-kit-1.0.3 에 반영 완료했습니다.

댓글 하이라이트와 키워드 하이라이트 선택 방식이 동일하여, 사용자가 선택하는 조건에 따라 다르게 반응해야 하는 상황입니다.
코드 구현의 어려움과 상호작용 조건이 까다로워 조작에도 여러움이 있어 다음과 같이 구성을 변경했습니다.

- 기존의 댓글 하이라이트 유지
- 섹션 하단에 '댓글 보기' 기능 추가
- 드래그 시 드래그 하이라이트 유지
- '댓글 보기' 온클릭 시 댓글 내용 보기
- '댓글 보기' 롱클릭 시 댓글 삭제 다이얼로그 표시
