### ISSUE TITLE
[BUG] FCM 토큰 제대로 동작하지 않습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#22]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

1. FCM 알림 토큰이 갱신이 되지 않습니다.
2. receiveMessage 콜백 메소드에서 "message"가 아닌 "body"로 받아야 합니다.
3. 공지, 이벤트 알림 설정 시 "notice", "event" 토픽에 가입되어야 합니다. (탈퇴도 마찬가지)
4. 앱 최초 접속 시 알림 권한을 물어봐야 하며, 회원가입 또는 로그인 시 적용되어야 합니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

- 없음

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

FCM 알림 토큰 정상 작동
- 현재, 테스트 메시지 작동하지 않음 (알림 권한, FCM 토큰 갱신 이슈)
- 공지, 이벤트 알림 작동하지 않음 (알림 권한, 토픽 가입 / 탈퇴 이슈)

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.3에 수정하여 반영하였습니다
- FCM 토큰 갱신 -> 수정 완료
- "message"를 "body"로 수정 -> 수정 완료
- 토픽 가입 -> 수정 완료
- 앱 최초 실행 시 권한 질의 기능 추가 및 회원 가입 시 반영 -> 수정 완료

- FCM 알림이 오지 않아 issue close는 하지 않겠습니다

**Comment by yyj1453** [comment]
- hotfix-yyj-1.0.3에 수정하여 반영하였습니다
