### ISSUE TITLE
[BUG] 댓글 작성 후 내 프로필 사진 및 닉네임이 이상하게 뜹니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#23]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

댓글 작성 후 작성된 댓글을 보면 프로필 사진 및 닉네임이 없고, 기본 프로필 사진이 뜹니다.
또는
프로필 사진은 잘 뜨지만 닉네임이 이상하게 뜨는 경우도 있습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 문서
2. 문서 상세
3. 댓글
4. 댓글 작성

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

닉네임, 프로필 사진이 정상적으로 떠야 합니다.

## 추가적인 설명
> 추가적으로 설명할 것이 있다면 설명해주세요,

![image](https://github.com/user-attachments/assets/b617c926-f850-4c02-91f7-017386ef281f)

**Comment by HaeBun** [comment]
하이라이트 로직 변경으로 hotfix 병합 후 작업 부탁드립니다. @yyj1453

**Comment by yyj1453** [comment]
- hotfix-yyj-1.0.3에 수정하여 반영하였습니다
- 병합 후에도 잘 작동됩니다
