### ISSUE TITLE
[BUG] 알림 목록에서 사용자 프로필 사진은 기본 사진입니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#24]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

알림 목록에서 보여지는 사용자 프로필 사진은 모두 기본 사진입니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 알림

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

사용자에 맞는 프로필 사진은 보여줘야합니다.

**Comment by yyj1453** [comment]
- hotfix-yyj-1.0.3에 수정하여 반영했습니다
