### ISSUE TITLE
[BUG] 문서 공유 인원 삭제 및 폴더 공유 인원 추가

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#26]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

1. 문서 추가 시 공유 인원 칸이 존재합니다.
2. 폴더 추가 시 공유 인원 칸이 존재하지 않습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 문서 업로드

1. 폴더 -> 폴더 추가

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

1. 문서 추가 시 공유 인원 칸이 삭제되어야 합니다.
2. 폴더 추가 시 공유 인원 칸이 추가되어야 합니다.

**Comment by yyj1453** [comment]
- 문서 추가 시 공유 인원 칸 삭제하였습니다

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.4에 수정하여 반영하였습니다
