### ISSUE TITLE
[Bug] 파일명이 길면 앱이 죽습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#28]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

문서 제목을 변경하였지만, 파일명이 길면 백엔드에서 title 길이 에러가 납니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 업로드

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

변경한 문서 제목으로 업로드해야 합니다.

**Comment by HaeBun** [comment]
hotfix-kit-1.0.4에 반영했습니다.
현재 subString으로 최대 32글자까지 전송되도록 변경되었습니다.
