### ISSUE TITLE
[BUG] 뒤로가기 버튼이 작동하지 않습니다.

### ISSUE THREAD

**Issue by dbstjdqls14** [Globa-Seoil-Univ/globa-android#29]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

문서 상세에서 더보기 버튼으로 이름 변경을 들어갔을 때, 좌상단 뒤로가기 버튼이 작동하지 않습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

문서 상세 -> 우상단 더보기 -> 이름 변경 -> 뒤로가기 미작동

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

뒤로 가기 버튼의 정상 작동

**Comment by HaeBun** [comment]
hotfix-kit-1.0.4 반영되었습니다.
이제 뒤로가기 클릭 시 이전 페이지(우상단 더보기) 화면으로 이동됩니다.
