### ISSUE TITLE
[BUG] 데이터가 없을 때 빈 화면이 출력됩니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#3]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

메인 화면, 폴더 내 문서 등 데이터가 없을 때 빈 화면이 추가됩니다. 데이터가 없다는 표시가 필요합니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 메인 화면
2. 폴더 내 문서 등

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

"데이터가 없습니다.", "최근에 사용한 문서가 없습니다." 등 안내 문구가 필요합니다.

## 추가적인 설명
> 추가적으로 설명할 것이 있다면 설명해주세요,

![KakaoTalk_20240915_105639120](https://github.com/user-attachments/assets/dd792a38-a22d-4f21-8d87-dd327a5c5cce)

**Comment by HaeBun** [comment]
hotfix-kit-v1.0.1 반영 완료했습니다.

**Comment by HaeBun** [comment]
![issue_3_2](https://github.com/user-attachments/assets/bf600023-03ac-4c7b-8b78-cfc91e27e05b)
![issue_3_1](https://github.com/user-attachments/assets/8ead43f3-f8bf-4fee-b724-889982ccaf8b)
