### ISSUE TITLE
[BUG] 시각화 자료의 중요도가 거꾸로 제공됩니다.

### ISSUE THREAD

**Issue by dbstjdqls14** [Globa-Seoil-Univ/globa-android#30]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

문서 상세의 시각화 자료 보기를 하였을 때, 중요도가 거꾸로 출력됩니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

문서 상세 -> 우상단 더보기 -> 시각화 자료 보기

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

백엔드가 던져준 순서대로 출력이 나와야합니다.

**Comment by dbstjdqls14** [comment]
![시각화1](https://github.com/user-attachments/assets/df3eea98-96c4-4e0b-9550-6a4d434f3f7e)
![시각화2](https://github.com/user-attachments/assets/9494a0c7-263f-47c9-be0b-bb07d02f431c)

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.4에 수정하여 반영하였습니다
