### ISSUE TITLE
[BUG] 뒤로가기 버튼이 작동하지 않습니다.

### ISSUE THREAD

**Issue by dbstjdqls14** [Globa-Seoil-Univ/globa-android#31]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

내 정보의 서비스 정보에 있는 버튼이 동작하지 않습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

내 정보 -> 서비스 정보 -> 좌상단 뒤로가기 버튼이 동작하지 않습니다.

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

정상적으로 내 정보 화면으로 나가져야 합니다.

![서비스정보1](https://github.com/user-attachments/assets/0b68e06c-af49-4ac4-a48d-69550a7e2574)

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.4에 수정하여 반영하였습니다
