### ISSUE TITLE
[BUG] 내 폴더의 권한 관리를 들어가면 앱이 작동하지 않습니다.

### ISSUE THREAD

**Issue by dbstjdqls14** [Globa-Seoil-Univ/globa-android#32]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

앱 내의 소유 권한이 있는 폴더에서 권한 관리를 들어갔을 때, 앱이 작동을 멈춥니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

폴더 탭 -> 내 소유의 폴더 접속 -> 더보기 -> 권한 관리 -> 앱 강제 종료됨

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

정상적으로 권한 관리 탭이 들어가져야 합니다.

![권한1](https://github.com/user-attachments/assets/a445f209-c7b9-4d74-a67a-a890ebf82c72)

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.4에 수정하여 반영하였습니다
