### ISSUE TITLE
[BUG] 댓글 작성 시 프로필 사진이 기본 프로필 사진입니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#33]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

댓글 작성 시 프로필 사진이 기본 프로필 사진입니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 문서
2. 하이라이트 클릭
3. 댓글 추가

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

사용자가 업로드한 프로필 사진이 떠야 합니다.

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.4에 수정하여 반영하였습니다
