### ISSUE TITLE
[BUG] 폴더 상세 정보의 생성 일자가 고정된 값을 출력합니다.

### ISSUE THREAD

**Issue by dbstjdqls14** [Globa-Seoil-Univ/globa-android#34]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

폴더의 더 보기를 누르면, 폴더 생성 일자가 고정된 값이 출력 됩니다,

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

폴더 탭 -> 아무 폴더나 접속 -> 더 보기 -> 고정된 생성 일자 출력

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

정상적인 폴더의 생성 일자가 출력되어야 합니다.

![폴더2](https://github.com/user-attachments/assets/474097cf-4743-453c-8b0c-e17937d9defd)

**Comment by HaeBun** [comment]
hotfix-kit-1.0.4 반영했습니다.

이제 제목과 날짜가 정확히 반영됩니다.![Screenshot_20240923_020316_Globa.jpg](https://github.com/user-attachments/assets/72a7316c-a8b4-40ad-9b21-c3fd8dfb36b4)
