### ISSUE TITLE
[BUG] 댓글 추가, 삭제 시 하이라이트가 바로 반영되지 않습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#36]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

댓글 추가, 삭제 시 하이라이트가 바로 반영되지 않습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 문서
2. 하이라이트 클릭
3. 댓글 모두 삭제 또는 추가

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

댓글 추가, 삭제 시 바로 하이라이트가 사라지거나, 추가되어야 합니다.

**Comment by yyj1453** [comment]
- 첫 댓글 추가 시 화면을 다시 로드 함으로서 해결했습니다

**Comment by yyj1453** [comment]
- 모든 댓글 삭제하고 댓글 창을 닫으면 화면을 다시 로드 함으로서 해결했습니다
