### ISSUE TITLE
[BUG] 메인화면 Swipe Refresh 기능 사용 시, 캐러셀이 이동합니다.

### ISSUE THREAD

**Issue by dbstjdqls14** [Globa-Seoil-Univ/globa-android#37]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

메인 화면 Swipe Refresh 기능 사용 시, 캐러셀이 우측하단으로 점점 이동합니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

메인 화면에서 Swipe Refresh를 반복 시도.

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

반복 시도 하여도 캐러셀 위치 고정이 되어야합니다.

![image](https://github.com/user-attachments/assets/d0007c51-e5d1-4118-806f-b3dd2ac4bfc7)

![image](https://github.com/user-attachments/assets/c8b6854c-278d-4eb8-8756-c7de1fcd517d)

![image](https://github.com/user-attachments/assets/15dc340f-605c-465a-945f-cb2a5832285d)

**Comment by HaeBun** [comment]
develop 에 반영했습니다.

캐러셀 사이즈 작업 중 삭제하지 않은 부분이 있었습니다.
