### ISSUE TITLE
[BUG] 댓글 권한 처리가 되어 있지 않습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#38]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

1. 읽기 권한인 사람이 댓글 작성하면 작성한 것처럼 화면이 업데이트 됩니다.
2. 읽기 권한인 사람이 댓글 삭제하면 삭제된 것처럼 화면이 업데이트 됩니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 문서
2. 하이라이트 클릭
3. 댓글 수정, 추가

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

1. 내 댓글 아니면 dialog 막기
2. errorCode : 40323이 오면 Toast Message로 읽기 권한은 수정 권한이 없다는 것 알리기.

**Comment by HaeBun** [comment]
develop 에 반영했습니다.

이제 본인의 댓글을 길게 눌렀을 때 댓글 삭제 및 수정 메뉴가 뜨도록 수정했습니다.
