### ISSUE TITLE
[BUG] 댓글 수정하면 해당 내용이 input 창에 반영되지 않습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#39]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

댓글 수정하면 해당 내용이 input 창에 반영되지 않습니다.
내가 댓글을 수정하고 있는 중인지를 알 수 없습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 문서
2. 하이라이트 클릭
3. 댓글 수정

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

변경하고자 하는 댓글 내용이 Edit Text 창에 반영되어야 합니다.

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.5에 수정하여 반영하였습니다
