### ISSUE TITLE
[BUG] 시스템 기본 테마가 다크모드 시 앱 내의 디자인이 깨집니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#4]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

시스템 기본 테마가 다크 모드일 시 앱 내 기본 디자인과 어울리지 못하는 현상이 발생합니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 설정
2. 돋보기 아이콘 (검색)
3. 다크 모드 
4. 다크 모드 설정에서 "다크" 클릭
5. 앱 실행

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

라이트 모드로 강제화 해야할 거 같습니다.

## 추가적인 설명
> 추가적으로 설명할 것이 있다면 설명해주세요,

![KakaoTalk_20240915_105639120_01](https://github.com/user-attachments/assets/962c31ed-bf01-479f-a23f-a783ebeeaa23)

**Comment by HaeBun** [comment]
라이트 모드로 강제화하여 v.1.0.1 반영했습니다.
