### ISSUE TITLE
[BUG] 검색 created_time 포맷팅이 필요합니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#41]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

2024-03-21T12:32:11라고 뜨고 있습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 검색

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

2024-03-21T12:32:11 -> 2024-03-21 12:32:11

**Comment by HaeBun** [comment]
develop 에 반영했습니다.

다음과 같이 변경되었습니다.![Screenshot_20240923_052622_Globa.jpg](https://github.com/user-attachments/assets/cdf34d44-2b8c-438c-a6dc-91e8aebeb7a9)
