### ISSUE TITLE
[BUG] 헤더의 세로 정렬이 가운데에 있지 않습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#7]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

헤더의 요소들이 세로 정렬을 지키지 못하고 있습니다.

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

헤더의 요소들 세로 정렬

## 추가적인 설명
> 추가적으로 설명할 것이 있다면 설명해주세요,

![KakaoTalk_20240915_105639120](https://github.com/user-attachments/assets/dd4c2a0e-5131-4bce-878f-1a8bee8fc51d)

**Comment by HaeBun** [comment]
hotfix-kit-v1.0.1 반영 완료했습니다.

**Comment by HaeBun** [comment]
![issue_7_1](https://github.com/user-attachments/assets/0c7aecaf-9af0-4a7b-8cc2-85e467a1288a)
