### ISSUE TITLE
[BUG] 알림 페이지에서 공지사항 탭으로 이동 시 앱이 죽습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#8]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

알림 페이지에서 공지사항 탭으로 이동 시 앱이 죽습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 헤더에 있는 알림 아이콘 클릭
2. 공지사항 탭

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

공지사항에 대한 알림을 가져옵니다.

**Comment by yyj1453** [comment]
hotfix-yyj-1.0.1에 반영하여 수정하였습니다
