### ISSUE TITLE
[BUG] 알림 공유 탭을 바로 진입하면 앱이 죽습니다.

### ISSUE THREAD

**Issue by seungyong** [Globa-Seoil-Univ/globa-android#9]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

알림 페이지에서 바로 공유 탭을 클릭하면 앱이 죽습니다. 단, 문의 등 다른 탭을 클릭 후 공유 탭을 클릭하면 앱이 죽지 않고 정상적으로 값을 가져옵니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 버그가 발생하는 실행 순서를 자세히 설명해주세요.

1. 헤더에 있는 알림 아이콘
2. 공유 탭

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

공유 관련 알림 가져오기

**Comment by yyj1453** [comment]
일시적인 오류라 판단되어 일단 close하겠습니다
